smile :)
timokau/marvins-playground pull request #21
Opened 2020-06-17 20:40 UTC by cole-h

Today is a good day.

2020-06-17 20:42 UTC, timokau commented
Indeed it is :upside_down_face: 

/marvin opt-in

2020-06-17 20:42 UTC, timokau commented
Oh, you would have to do that. Well, let me cheat.

2020-06-17 20:42 UTC, cole-h commented
/marvin opt-in

2020-06-17 20:43 UTC, timokau commented
Hah, I probably outran it by a millisecond or two.

2020-06-17 20:43 UTC, timokau commented
/marvin needs_review

2020-06-17 20:43 UTC, timokau commented
I keep mixing that up

/state needs_review

2020-06-17 20:44 UTC, timokau commented
/status needs_review
... you'd think I know the commands

2020-06-17 20:45 UTC, timokau commented
Oh, it crashed. Good thing I tried it here first.

2020-06-17 20:47 UTC, timokau commented
/status needs_review

2020-06-17 20:51 UTC, timokau commented
Third time's the charm.
/status needs_review

2020-06-17 20:51 UTC, timokau requested changes

2020-06-17 20:51 UTC, timokau commented on smile
> +:)
Needs more emoji.

2020-06-17 20:54 UTC, timokau commented
Actually ascii art might be fine.
/status needs_review

2020-06-17 20:54 UTC, timokau requested changes
Or is it?

2020-06-17 20:56 UTC, timokau reviewed
I think I like it.
/status needs_merge

2020-06-17 21:04 UTC, cole-h commented
I've added an ASCII art smiley. PTAL.

```
                    *****************
               ******               ******
           ****                           ****
        ****                                 ***
      ***                                       ***
     **           ***               ***           **
   **           *******           *******          ***
  **            *******           *******            **
 **             *******           *******             **
 **               ***               ***               **
**                                                     **
**       *                                     *       **
**      **                                     **      **
 **   ****                                     ****   **
 **      **                                   **      **
  **       ***                             ***       **
   ***       ****                       ****       ***
     **         ******             ******         **
      ***            ***************            ***
        ****                                 ****
           ****                           ****
               ******               ******
                    *****************

(taken from https://www.asciiart.eu/computers/smileys)

```

2020-06-17 21:12 UTC, timokau commented
:laughing: 
/status needs_review
That makes me think that pushes should reset `needs_merge` -> `needs_review`.

2020-06-17 21:22 UTC, timokau commented
/status needs_merge

2020-06-17 21:28 UTC, timokau commented
It should do that now. Love the ascii art!
/status needs_merge

2020-06-17 21:30 UTC, cole-h commented
Looks like it works!

2020-06-17 21:31 UTC, timokau commented on frown
> +:(
:(
At least the proportions are appropriate :)

2020-06-17 21:33 UTC, timokau commented
Well, that should be enough bot development for today. Thanks for the help :)

2020-06-17 21:34 UTC, cole-h commented
Happy to! If you need more ~~victims~~ testers, feel free to ping. I'm on IRC most of the time ;-)

2020-06-17 21:40 UTC, timokau commented
Thanks! I think at this point its probably best to wait for some real-world usage and see how well it works for people.

2020-06-18 18:43 UTC, timokau requested changes

2020-06-18 18:43 UTC, timokau commented on frown
> +(taken from https://www.asciiart.eu/computers/smileys)
```
  , ; ,   .-'"""'-.   , ; ,
  \\|/  .'         '.  \|//
   \-;-/   ()   ()   \-;-/
   // ;               ; \\
  //__; :.         .; ;__\\
 `-----\'.'-.....-'.'/-----'
        '.'.-.-,_.'.'
jgs       '(  (..-'
            '-'
``` (same [source](https://www.asciiart.eu/computers/smileys))

Testing a fix for https://github.com/nix-community/infra/pull/30#issuecomment-645673503.

2020-06-18 18:43 UTC, timokau commented
/marvin opt-in
/status needs_review

2020-06-18 18:44 UTC, timokau commented
/marvin opt-in

2020-06-18 18:44 UTC, timokau commented
Oh, I forgot again.

2020-06-18 18:44 UTC, timokau commented
/status needs_review

2020-06-18 18:45 UTC, timokau approved these changes

2020-06-18 18:45 UTC, timokau requested changes

2020-06-18 18:45 UTC, timokau commented on frown
> +(taken from https://www.asciiart.eu/computers/smileys)
\o/

2020-06-18 18:46 UTC, timokau commented
Good bot.

2020-06-19 18:45 UTC, timokau commented
/status needs_merge

2020-06-19 18:48 UTC, timokau commented
/status needs_merge

2020-06-19 18:52 UTC, timokau commented
(trying to get the bot to request a review)
/status needs_merge

2020-06-19 18:57 UTC, cole-h commented
Assuming you're trying to get it to request you as the reviewer: Is there a chance that the bot doesn't support *re*-requesting, since you've already "reviewed" this? (Also note that authors cannot "review" their own PR if you were trying to request me...)

2020-06-19 19:03 UTC, timokau commented
Yes I'm trying to request me. Its possible that it may be an issue that I have an outstanding review, that's one of the things I want to test. But for now the issues are more mundane (i.e. related to getting the right API request and juggling githubs data).
/status needs_merge

2020-06-19 19:05 UTC, timokau commented
I'm surprised that `mypy` can't detect wrong argument order of `hasattr`...
/status needs_merge

2020-06-19 19:09 UTC, timokau commented
/status needs_merge

2020-06-19 19:13 UTC, timokau commented
Hopeful for this one
/status needs_merge

2020-06-19 19:20 UTC, timokau commented
I'm sure you can do it marvin!
/status needs_merge

2020-06-19 19:22 UTC, timokau commented
Well, this time though.
/status needs_merge

2020-06-19 19:23 UTC, timokau commented
Very close, just didn't bring your credentials. It'll work next time.
/status needs_merge

2020-06-19 19:24 UTC, timokau commented
What if we try to do it again?
/status needs_merge

2020-06-19 19:30 UTC, cole-h commented
If you don't already, I think removing some flags (like `needs_merge`) on conversion to and from a draft PR is a good idea.

2020-06-19 19:35 UTC, timokau commented
Yeah, agreed. We're review-bound, so I'm tending towards automating going "down the chain" as much as possible while keeping going "up the chain" explicit.

2020-06-19 19:36 UTC, timokau commented
I'll focus on the review requests first though, since that will provide an actual incentive to use it ;)

2020-06-19 19:52 UTC, timokau commented
@cole-h I temporarily [signed you up](https://github.com/timokau/marvin-mk2/pull/21/files#diff-7cc9cf4bc2576f1fe8e54fd6f45d2ef5R49) for review requests to test the selection ;) Hopefully it'll request you in 50% of the cases now. Doesn't make sense to request you for your own PR of course, but that's now the point of the test :smile: 
/status needs_merge

2020-06-19 19:53 UTC, timokau commented
/status needs_merge

2020-06-19 19:53 UTC, timokau commented
/status needs_merge

2020-06-19 19:54 UTC, timokau commented
I should calculate how often I have to run this until I can be 99.99% sure there is a bug
/status needs_merge

2020-06-19 19:54 UTC, timokau commented
/status needs_merge

2020-06-19 19:55 UTC, timokau commented
0.5 ** 5 = 0.03125
Getting unlikely
/status needs_merge

2020-06-19 19:58 UTC, timokau commented
/status needs_merge

2020-06-19 20:00 UTC, timokau commented
/status needs_merge

2020-06-19 20:06 UTC, timokau commented
```
2020-06-19T20:05:41.025436+00:00 app[web.1]: Shuffled: ['cole-h', 'timokau']
2020-06-19T20:05:41.025549+00:00 app[web.1]: Shuffled: ['cole-h', 'timokau']
2020-06-19T20:05:41.025641+00:00 app[web.1]: Shuffled: ['cole-h', 'timokau']
2020-06-19T20:05:41.025720+00:00 app[web.1]: Shuffled: ['cole-h', 'timokau']
2020-06-19T20:05:41.025798+00:00 app[web.1]: Shuffled: ['cole-h', 'timokau']
2020-06-19T20:05:41.025874+00:00 app[web.1]: Shuffled: ['cole-h', 'timokau']
2020-06-19T20:05:41.025950+00:00 app[web.1]: Shuffled: ['cole-h', 'timokau']
2020-06-19T20:05:41.026028+00:00 app[web.1]: Shuffled: ['cole-h', 'timokau']
2020-06-19T20:05:41.026105+00:00 app[web.1]: Shuffled: ['cole-h', 'timokau']
2020-06-19T20:05:41.026181+00:00 app[web.1]: Shuffled: ['timokau', 'cole-h']
```

Python's `random`, are you okay?

2020-06-19 20:08 UTC, cole-h commented
https://xkcd.com/221/

2020-06-19 20:14 UTC, timokau commented
Okay seems like that actually works okay and I just forgot about what you said [previously](https://github.com/timokau/marvins-playground/pull/21#issuecomment-646817157) :facepalm: 

It told me it would've picked you though, so :shrug:

2020-06-19 20:41 UTC, timokau commented
Should no longer attempt to request reviews from the PR author.
/status needs_merge

2020-06-19 20:45 UTC, timokau commented
And it doesn't :)

2020-06-19 22:19 UTC, timokau requested changes
For some reason the changes requested -> needs_work didn't work on https://github.com/NixOS/nixpkgs/pull/89235

2020-06-19 22:23 UTC, timokau commented
https://github.com/timokau/marvin-mk2/pull/25
Too bad, so commands in reviews won't work after all in this deploy.

2020-07-01 21:35 UTC, timokau commented
/marvin opt-in
/status needs_reviewer

2020-07-01 21:35 UTC, timokau commented
/status needs_reviewer

2020-07-01 21:36 UTC, timokau commented
Doing reviewery things.

2020-07-01 21:39 UTC, timokau commented
/status awaiting_changes

2020-07-01 21:40 UTC, timokau commented
/status awaiting_reviewer

2020-07-01 21:40 UTC, timokau reviewed
Some feedback

2020-07-01 21:45 UTC, timokau requested changes
Some other feedback (not sure if "Comment" reviews should trigger the status change).

2020-07-01 21:46 UTC, timokau commented
@cole-h, please leave a comment. Testing https://github.com/timokau/marvin-mk2/issues/29 (I'm finishing up for today though, so I won't be responsive for now).

2020-07-01 22:09 UTC, cole-h reviewed
This kind of comment?

2020-07-01 22:09 UTC, cole-h commented
Or this kind of comment?

2020-07-02 03:21 UTC, cole-h commented
I'm not really a fan of a comment implicitly changing state (e.g. without the presence of an explicit `/marvin do_something`). As you can see above, I contributed nothing of value that would require another review. I feel like it adds noise where there doesn't need to be any.

2020-07-02 10:18 UTC, timokau commented
Yes, its a heuristic. But the difference between `awaiting_reviewer` and `awaiting_changes` is only important when the PR is going stale. `awaiting_changes` is basically  the sink for abandoned PRs we can forget about. Stale `awaiting_reviewer` PRs will be triaged and assigned a new reviewer.

Since I want to avoid letting PRs slip through the cracks, I'd rather put them into the review queue one time too much. A reviewer can then set it back to `awaiting_changes`, where it'll stay as long as the PR author is inactive. The issue with explicit commands is that
- people forget to use them or they
- don't use them because they're perceived as "rude" (when sending a PR "down the ladder") and
- they add additional noise that actually reaches you through notifications.

So in summary, people really only have to care about the `needs_reviewer` and `needs_merger` state. They can mentally combine `awaiting_*` to `in_review`. The differences are only important for automatic triage, where some false-positives are okay. The goals are to avoid PRs getting stuck and optimize for the "reviewer with commit bit" bottleneck.

Given this justification, do you still think explicit commands would be better?

2020-07-02 10:19 UTC, timokau commented
In the new model, explicit commands are only needed for opt-in, non-committer review (`-> needs_merger` transitions are still explicit to optimize for the bottleneck) and when the heuristic fails (for example a PR author wants to request another reviewer with `/status needs_reviewer`).

2020-07-02 10:20 UTC, timokau commented
(Something seems to be wrong here, not sure what the bot is doing. Good thing we're having this conversation here).

2020-07-02 17:18 UTC, cole-h commented
I think the justification is fair, now that you've explained it. Not to say I like it (heuristics give me the heebie-jeebies), but it's fair.

2020-07-02 19:21 UTC, timokau commented
> I think the justification is fair, now that you've explained it. Not to say I like it (heuristics give me the heebie-jeebies), but it's fair.

Good :) Lets see how it works in practice. An alternative would be to always make the `needs_changes` transitions explicit, but that would need a bit more reviewer capacity. `needs_changes` would then kind of be a soft stale label.

> (Something seems to be wrong here, not sure what the bot is doing. Good thing we're having this conversation here).

Ohh I actually had a command in my message without realizing it. Maybe it was better to require them to be in their own line, not sure. Either way, no bug here.

2020-07-02 22:02 UTC, timokau commented
/status needs_reviewer

2020-07-02 22:02 UTC, timokau commented
/marvin triage

2020-07-02 22:07 UTC, timokau commented
/marvin triage

2020-07-02 22:12 UTC, timokau commented
/marvin triage

2020-07-02 22:13 UTC, timokau commented
Good bot! (Well, `awaiting_changes` was not intended but assigning reviewers is nice).

2020-07-14 19:28 UTC, timokau commented
Testing some changes in determining reviewer availability (https://github.com/timokau/marvin-mk2/issues/71).
/status needs_reviewer

2020-07-14 19:29 UTC, timokau commented
/status awaiting_changes

2020-07-14 19:30 UTC, timokau commented
/status needs_reviewer

2020-07-14 19:31 UTC, timokau commented
/status awaiting_changes

2020-07-14 19:31 UTC, timokau commented
/status needs_reviewer

2020-07-14 19:32 UTC, timokau commented
That worked surprisingly well on first try. Good bot.
/status awaiting_changes

2020-07-14 20:48 UTC, timokau commented
Didn't work quote that well after all: https://github.com/timokau/marvin-mk2/pull/80

2022-04-16 20:28 UTC, closed without merging